# Generated by Django 6.0.1 on 2026-01-28 19:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CrashEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("occurrence_count", models.PositiveIntegerField(default=1)),
                ("level", models.CharField(blank=True, db_index=True, max_length=32)),
                ("logger", models.CharField(blank=True, db_index=True, max_length=255)),
                (
                    "error_type",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("message", models.TextField(blank=True)),
                (
                    "request_path",
                    models.CharField(blank=True, db_index=True, max_length=2048),
                ),
                ("request_method", models.CharField(blank=True, max_length=16)),
                (
                    "user_identifier",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("remote_addr", models.CharField(blank=True, max_length=64)),
                ("traceback", models.TextField()),
                ("traceback_hash", models.CharField(max_length=64, unique=True)),
                ("context", models.JSONField(default=dict)),
                (
                    "server_name",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("culprit", models.CharField(blank=True, max_length=512)),
            ],
            options={
                "ordering": ["-last_seen_at"],
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="django_cras_created_1ce45b_idx"
                    ),
                    models.Index(
                        fields=["last_seen_at"], name="django_cras_last_se_94ed8a_idx"
                    ),
                    models.Index(fields=["level"], name="django_cras_level_62a6b6_idx"),
                    models.Index(
                        fields=["logger"], name="django_cras_logger_e527b9_idx"
                    ),
                    models.Index(
                        fields=["error_type"], name="django_cras_error_t_b9f34d_idx"
                    ),
                    models.Index(
                        fields=["request_path"], name="django_cras_request_2f726b_idx"
                    ),
                    models.Index(
                        fields=["user_identifier"],
                        name="django_cras_user_id_ed1547_idx",
                    ),
                ],
            },
        ),
    ]
